name: Build and Deploy (code lỏ hì hì)

on:
  push:
    branches:
      - main
 
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
   
    - name: Install dependencies and build front-end
      # if: ${{ contains(github.event.head_commit.modified, 'front-end/') }}
      run: |
        cd front-end
        npm install
        npm run build

    - name: Deploy front-end
      # if: ${{ contains(github.event.head_commit.modified, 'front-end/') }}
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "front-end/build/*"
        target: "${{ secrets.front-end_DEPLOY_PATH }}"

    - name: Install dependencies and build back-end
      # if: ${{ contains(github.event.head_commit.modified, 'back-end/') }}
      run: |
        cd back-end
        npm install
        npm run prop

    - name: Deploy back-end
      # if: ${{ contains(github.event.head_commit.modified, 'back-end/') }}
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "back-end/dist/*,back-end/Images"
        target: "${{ secrets.back-end_DEPLOY_PATH }}"
